icepack/plot.py

I was getting an index error on plotting the mesh, resulting from an implicit requirement in the plotting code that edges are numbered sequentially starting at 1. I don't generally number edges sequentially in gmsh, and it seems that gmsh and the rest of icepack don't require it, so I changed the mesh plotting to color the edges without requiring a certain numbering.

Fix edge coloring so that sequential numbering is not required

---

doc/source/installation.rst
requirements.txt

Firedrake provides inbuilt support for installing icepack. This means Firedrake and icepack can be installed in a single line, which makes the icepack install instructions shorter.
As an aside, I note that the icepack install instructions also install umfpack. Firedrake builds mumps into PETSc to provide a good parallel direct solver. Is there something about umfpack which means we need that in addition to mumps?

Icepack install tweaks

---

demo/02-larsen-ice-shelf.ipynb
demo/04-ice-shelf-inverse.ipynb
demo/data.py
demo/mesh.py
doc/Makefile
requirements.txt
setup.py

This patch eliminates nearly all the functions of the icepack-data repo, which makes running the demos a lot simpler for the average user.

eliminating icepack-data repo

---

icepack/models/hybrid.py
icepack/models/ice_shelf.py
icepack/models/ice_stream.py
icepack/models/mass_transport.py
icepack/utilities.py
test/mass_transport_test.py

Adds a Lax-Wendroff time-stepping scheme for the mass transport equation in addition to the implicit Euler scheme. This scheme converges at higher order and has better stability properties than implicit Euler The flow models now include an optional argument for which mass transport scheme they use.

Lax-Wendroff

---

demo/02-larsen-ice-shelf.ipynb
demo/04-ice-shelf-inverse.ipynb
icepack/datasets.py
icepack/interpolate.py
icepack/plot.py

Use the new [BedMachine](https://nsidc.org/data/NSIDC-0756/versions/1) dataset for Antarctica, which incorporates new observations that were not available when bedmap2 was compiled. Switching to the new dataset required changing the mesh for Larsen C and applying a smoothing filter to avoid some unphysical values of the ice thickness due to rifts, firn, etc.

switching from bedmap2 to BedMachine Antarctica

---

.circleci/config.yml

This patch pulls in a newer docker image for testing that has gmsh installed. This way we can use more sophisticated geometries in the test suite or run the synthetic demos as part of the tests.

Updating testing environment

---

demo/03-synthetic-ice-stream.ipynb
icepack/models/friction.py
icepack/models/hybrid.py
icepack/models/ice_shelf.py
icepack/models/ice_stream.py
icepack/models/viscosity.py
test/ice_shelf_test.py

Resolves #30 and removes a whole mess of repeated code in the hybrid model. For example the kernel of the basal friction part of the action is the same for both the hybrid model and for the shallow stream equations, but the measure is different -- `dx_b` for the hybrid model and `dx` for shallow stream. Before, these had to be two different functions, whereas now they're the same.
With the old way of doing things, a user could change what part of the domain a component of an action functional was integrated over. That will no longer be possible with this patch but I think that's for the best -- a change that drastic warrants an entirely new model.
This patch doesn't quite make the improvements I was hoping for with the damage mechanics model, but it cleans things up so I think it's still …

change where measures are applied to action functionals

---

demo/03-synthetic-ice-stream.ipynb
demo/05-hybrid-ice-stream.ipynb
icepack/__init__.py
icepack/models/hybrid.py
icepack/models/ice_stream.py
icepack/utilities.py
test/ice_stream_test.py
test/mass_transport_test.py

The `compute_surface` function lives in two places, the ice stream model and the hybrid model. This patch lifts them into the `icepack` module which cuts some repeated code. Calling it through the model objects now gives a deprecation warning.

move compute surface function

---

demo/04-ice-shelf-inverse.ipynb
icepack/inverse.py

This patch fixes some potential problems when the inverse solver is very near or at a local minimum:
* The `_bracket` function can enter an infinite loop if the solver has reached a local minimum.
* The solver does nothing to check whether the Newton decrement is actually negative.
These have both been fixed and I've added a new convergence criterion based on the Newton decrement.
I've also updated the inverse demo to suggest that users print out the Newton decrement as part of the solver callback.
This can help as a smoke test for potential convergence failure or really bad conditioning.

New convergence criterion for inverse solve

---

icepack/models/damage_transport.py
icepack/models/heat_transport.py
icepack/models/hybrid.py
icepack/models/ice_shelf.py
icepack/models/ice_stream.py
icepack/models/mass_transport.py
icepack/models/shallow_ice.py
icepack/utilities.py

By default, Python [doesn't show DeprecationWarning](https://docs.python.org/3/library/warnings.html#default-warning-filter). The argument is that these are often buried deep down in dependencies of dependencies, and end users shouldn't get a bunch of cryptic terminal output for something that's a developer's job to fix. You can view them by calling a script with `python3 -Wd`, which was a new one on me. We need users to know if they're calling functionality that's soon to be removed, so this patch changes all deprecation warnings to FutureWarning, which is actually visible.

Make warnings louder

---

icepack/models/hybrid.py
icepack/models/ice_shelf.py
icepack/models/ice_stream.py
icepack/models/shallow_ice.py
icepack/optimization.py
icepack/solvers/flow_solver.py
test/hybrid_test.py
test/ice_shelf_test.py
test/ice_stream_test.py
test/mass_transport_test.py
test/shallow_ice_test.py

Revert commits:
* 6167dd02df7094b70d668a45762fc35cd342c28d
* ac37ab73521e73545982110782405cf04729d39b
* e4d9c3b4d4e4b30b4e2254d56204539f6b076f52
* ce922849a71ebf3f09a3854a08213b719104ac27
* f8ed459946b1f4245c3981dfe1613c037c5d33af
Transitioning to PETSc SNES was too hasty; the hand-written optimization
solver appears to be more robust to the kind of pathological input data
that one encounters at intermediate stages of an inverse solver. It
might be feasible to switch to PETSc SNES at a later date but this will
require either trust region methods or bounds-constrained optimization
to keep the parameters guesses sensible.

Revert back to bespoke optimization solver

---

MANIFEST.in
icepack/datasets.py
icepack/registry.txt
setup.py

This patch switches us to using a separate registry text file to describe the datasets to download from NSIDC rather than hard-coding the filenames, URLs, and hashes into datasets.py. See [this page](https://www.fatiando.org/pooch/latest/usage.html#so-you-have-1000-data-files) from the pooch documentation for more on registry files.
Making this change will help us move towards automated testing using real observational data, rather than just synthetic problems. The datasets we use (BedMachine, MEaSUREs Antarctica) are often 4GB or more. Downloading them every time or baking them into the Docker image is impractical We can instead take subsets of these maps for, say, Larsen or Pine Island using `rio warp`. These smaller chunks are more like ~16MB each. We can then bake these into the …

switch to using pooch dataset registry file

---

icepack/solvers/flow_solver.py
icepack/solvers/heat_transport.py
test/heat_transport_test.py
test/ice_shelf_test.py

This patch does what #50 should have. The responsibility for solving the diagnostic equations has been factored out into a separate class which defaults to the existing implementation -- a handwritten Newton line search optimization solver. Alternatively, you can opt to use PETSc SNES. In the future we might support a PETSc TAO solver as well.
In either case you can now pass solver parameters, for example to make simulations run faster by using the conjugate gradient method with an appropriate preconditioner. I get ~25% speed-ups on the MISMIP+ test case with very little effort this way.
Finally, this should offer a workaround for people who have had troubles on MacOS with different versions of the gfortran runtime library getting linked through MUMPS and scipy (attn @jabadge ). You'd …

Factor out diagnostic solver from FlowSolver and add hooks for solver options

---

icepack/models/mass_transport.py
test/mass_transport_test.py

During the switch to the new flow solver interface, I accidentally broke the use case where a simulation has no inflow boundary, for example an entire ice cap. This patch fixes that use case and adds a test using the shallow ice model.

Handle case of no inflow in mass transport

---

requirements.txt
setup.py

gmsh requires a full graphics stack and loads several dynamic libraries
that might not exist in a containerized environment. This patch only
imports pygmsh inside the `collection_to_geo` function so that icepack
can still be imported if a user never intends to call that function.

Conditionally import pygmsh

---

test/shallow_ice_test.py

I updated shallow_ice_test.py to use the UnitDiskMesh generator from firedrake rather than a circular mesh created with gmsh. I also lowered the penalty in the shallow ice action functional so that the numerical solution that is being tested undergoes less smoothing (it still undergoes smoothing on the order of one ice thickness). I have kept the feature that restricts the test to the central 56.25% of the ice sheet (by area).

Update shallow ice test with new mesh and lower penalty

---

notebooks/tutorials/00-meshes-functions.ipynb
notebooks/tutorials/01-synthetic-ice-sheet.ipynb
notebooks/tutorials/02-synthetic-ice-shelf.ipynb
notebooks/tutorials/03-larsen-ice-shelf.ipynb
notebooks/tutorials/04-synthetic-ice-stream.ipynb
notebooks/tutorials/05-ice-shelf-inverse.ipynb
notebooks/tutorials/06-hybrid-ice-stream.ipynb

This patch switches the tutorials to mostly using tripcolor instead of tricontour(f). Since tripcolor now defaults to Gouraud rather than flat shading, this is a much better option for most visualizations. I've also added a description of the kinds of bump and ramp functions that we use in all the synthetic glacier simulations to the 0th tutorial.

documentation improvements

---

icepack/meshing.py
notebooks/how-to/03-adaptivity.ipynb
setup.py
test/meshing_test.py

Resolves #53 although not by the method suggested there. I had tried to implement r-refinement as described in that issue but wasn't able to write a solver for the Monge-Ampere equations that worked very well. Instead, this patch adds some glue code to talk to MeshPy, which in turn provides an interface to the mesh generator Triangle. Triangle makes it simple to take an initial mesh and specify the desired triangle areas for a refined mesh. This is possible but much more cumbersome with gmsh. I've also added a how-to guide that shows how to do adaptive refinement using MISMIP+ as a test case.

mesh refinement how-to guide

---

icepack/calculus.py
icepack/models/damage_transport.py
icepack/models/friction.py
icepack/models/heat_transport.py
icepack/models/hybrid.py
icepack/models/ice_shelf.py
icepack/models/ice_stream.py
icepack/models/mass_transport.py
icepack/models/shallow_ice.py
icepack/models/viscosity.py
icepack/solvers/flow_solver.py
icepack/utilities.py

This patch pulls all of the specialized vector calculus operators that @benhills added to support flowband models into their own module. I also added functions for the trace of a matrix and to create the Identity matrix. This makes it possible to get rid of the conditionals in the definition of the viscous action for both depth-averaged or 3D models.

Refactor vector calculus operators

---

.circleci/config.yml
notebooks/tutorials/03-larsen-ice-shelf.ipynb
notebooks/tutorials/05-ice-shelf-inverse.ipynb

Use a new version of the testing image with fixes to Firedrake for the warnings about wrapping the entire numpy random number generator API. Also eliminate the use of some old deprecated functions.

Container version

---

.circleci/config.yml

Gets us to a Firedrake version after the loopy sprint, exchanging one set of warnings for another.

Bump container version

---

icepack/models/hybrid.py
icepack/models/ice_shelf.py
icepack/models/ice_stream.py
icepack/models/shallow_ice.py
icepack/solvers/flow_solver.py

Before, quadrature degree setting occured inside FlowSolver. This has the unfortunate effect of leaving the firedrake-adjoint with no way to know what quadrature degree to use, barring upstream fixes. The solver for the adjoint equation then uses the default, conservative quadrature estimation, resulting in annoying warnings and low performance. This patch puts quadrature degree in by adding it to the metadata of all the measures (dx, ds, etc.) in the action functionals.

Move quadrature degree estimation from solver to models

---

.circleci/config.yml
icepack/__init__.py
icepack/statistics.py
notebooks/how-to/04-sparse-data.ipynb
notebooks/how-to/05-time-dependent-inverse.ipynb
notebooks/tutorials/05-ice-shelf-inverse.ipynb
test/statistics_test.py

This PR adds a new module statistics.py which defines the classes StatisticsProblem and MaximumProbabilityEstimator. These are analogous to the InverseProblem/InverseSolver classes but for the fact that they use pyadjoint instead of the hand-coded adjoint calculation from before. This makes it possible to use the Firedrake VertexOnlyMesh features to do sparse data assimilation and to do time-dependent data assimilation. We now have a hard dependency on ROL to do the optimization. There are also two new tutorials on sparse and time-dependent data assimilation respectively.
The limitations are:
* have to use the PETSc diagnostic solver instead of the hand-written one in icepack, the latter of which is more robust on some inputs
* have to use ROL to do the optimization, for which our only …

Time-dependent adjoint

---

icepack/plot.py

vmin and vmix are expected to scale the colors in icepack.plot.streamplot (the kwargs are used in tutorial 05, so it seems that the intention is for them to be valid). Previously, these were ignored by automatically scaling with max_speed. Now, they should behave as normal for matplotlib.

Fix unexpected vmin/vmax behavior with streamplot

---

icepack/interpolate.py
test/grid_data_test.py

I think this is a safe fix for #95. This should allow, for example, the bed, surface, or 2D velocity field to be interpolated onto a function space for a 3D mesh (and works at least with `vfamily="R"`, `vfamily="GL"`, and `vfamily="CG"` with varying `vdegree`).

Interpolate 2D rasters to 3D meshes

---

icepack/meshing.py
notebooks/how-to/03-adaptivity.ipynb

We need to add `reorder=False` when creating the DMPlex in order to guarantee that the cells of the Firedrake and Triangle meshes are numbered the same way. The numbering has to be the same if we want to use some expression on the Firedrake side to determine how to refine the Triangle mesh.

bug fix in Triangle mesh translation

---

icepack/meshing.py
icepack/statistics.py

The `val` member of ROLObjective was made private. Resolves dolfin-adjoint/pyadjoint#89.

Update ROL shims for new pyadjoint API

---

icepack/models/friction.py
icepack/models/hybrid.py
test/hybrid_test.py

As best I can tell, it was not possible to use sidewall drag on a flowline since there is no sidewall id when the whole domain is a sidewall. I think this a pretty common use case for sidewall drag, since you get pretty fast velocities near termini otherwise. It has a good history of use (e.g., Gagliardini et al., 2010).
I simply changed things to make the whole domain a sidewall by default for XZ in the hybrid model, with drag coefficient equal to zero. In this case there is no normal vector to the wall, so I had to create a new type of friction as well (inelegant, but works). I didn't touch the SSA, though, so maybe that should be done before merging?
Also I think it is worth a test to be sure that this does not affect velocities as long as side_friction=0.0, but I am not sure how best …

Sidewall drag for flowlines

---

requirements.txt
setup.py

Installing Trilinos and ROL from pypi fails with recent C++ compilers and Python versions. This patch updates the icepack dependencies to use patched versions of these libraries.

Use our own fork of Trilinos and pyrol

---

.github/workflows/test.yml
pyproject.toml

We remain pinned to meshio-4.4.6, which uses the `numpy.string_` class. This type has been removed from numpy-2.0 in favor of `numpy.bytes_`. This patch switches to using a fork I made of meshio that fixes the bug on numpy-2.0.

Temporary workaround for pygmsh-6.x + numpy-2.0

---

.github/workflows/test.yml
notebooks/how-to/03-adaptivity.ipynb
notebooks/how-to/04-sparse-data.ipynb
notebooks/tutorials/00-meshes-functions.ipynb
notebooks/tutorials/02-synthetic-ice-shelf.ipynb
notebooks/tutorials/03-larsen-ice-shelf.ipynb
notebooks/tutorials/05-ice-shelf-inverse.ipynb
notebooks/tutorials/07-rgi-meshing.ipynb
pyproject.toml
src/icepack/meshing.py
test/meshing_test.py

Resolves #82, deprecates `icepack.meshing.collection_to_geo`, and makes dependency on pygmsh optional. Pygmsh appears to no longer be maintained.

Update to using gmsh python API

---

src/icepack/datasets.py

NASA is moving to using the Common Metadata Repository for all public data. Eventually we should switch to using [earthaccess](https://earthaccess.readthedocs.io) for this.

Fix some NSIDC urls
