icepack/icepack

- geotiff.py
- icepack/grid/geotiff.py
A simple reader/writer for geotiffs (should be able to read any GDAL-readable file).
> Add geotiff reader

- test/hybrid_test.py
- test/mass_transport_test.py
This patch adds some output to the hybrid model test. If there's no output for 10 min, travis will assume that the tests are stuck and time out.
> Adding some output to hybrid test

- icepack/constants.py
- icepack/models/__init__.py
- icepack/models/heat_transport.py
- icepack/models/hybrid.py
- icepack/utilities.py
- test/heat_transport_test.py
This patch adds a simplified heat transport solver using the enthalpy method of Aschwanden 2012.
> heat transport solver

- demo/02-larsen-ice-shelf.ipynb
- demo/04-ice-shelf-inverse.ipynb
- demo/data.py
This patch adds the MODIS Mosaic of Antarctica image as a background to all the demos for the Larsen Ice Shelf.
> Using satellite images for Larsen demos

- demo/02-larsen-ice-shelf.ipynb
- demo/04-ice-shelf-inverse.ipynb
- demo/data.py
The old mesh was missing an ice rise that's hard to see in bedmap2 but much more obvious from REMA.
> Using new mesh for Larsen

- icepack/plot.py
- test/plot_test.py
Also switch to using an internal firedrake function for calculating field values rather than `function.at`, which is brittle.
> Adding tricontour and tripcolor

- .circleci/config.yml
- README.md
- test/plot_test.py
* Switch to a new docker image that uses MPICH instead of OpenMPI. While OpenMPI is supposedly faster, MPICH is more stable and less bug-prone.
* Add code coverage measurement to the test suite using codecov.io.
> testing improvements

- icepack/models/damage_transport.py
- icepack/utilities.py
- test/test_damage.py
Corrections to parts of the Levermann damage physics model
> damage fixes

- demo/01-synthetic-ice-shelf.ipynb
- demo/02-larsen-ice-shelf.ipynb
- demo/04-ice-shelf-inverse.ipynb
Use a more straightforward parameterization of the fluidity in demo 4 and adjust the regularization parameter. Also fix a plotting goof in demo 2.
> Demo fixes

- demo/01-synthetic-ice-shelf.ipynb
- demo/02-larsen-ice-shelf.ipynb
- icepack/datasets.py
- requirements.txt
- setup.py
This PR makes some general improvements to the documentation and examples. These include:
* more explanation of the damage mechanics model
* using new functions from pooch to give feedback on downloading data sets
* better explanations of some of the pre-processing routines for real data
> datasets & documentation improvements

- .circleci/config.yml
- demo/00-meshes-functions.ipynb
- demo/01-synthetic-ice-shelf.ipynb
- demo/02-larsen-ice-shelf.ipynb
- demo/04-ice-shelf-inverse.ipynb
- icepack/plot.py
- test/plot_test.py
Some of the features in icepack/plot.py have been upstreamed into Firedrake. This patch removes them from icepack and updates the Docker image for testing.
> update for Firedrake plotting improvements

- icepack/models/__init__.py
- icepack/models/shallow_ice.py
- test/shallow_ice_test.py
I added a new ice flow model to icepack, the shallow ice approximation. In icepack, the model is called shallow_ice. I have additionally created a test for the convergence of the shallow_ice diagnostic solver.
> Shallow Ice model

- icepack/inverse.py
This patch replaces all instances of `firedrake.solve` in the inverse module with pairs of LinearVariationalProblem + LinearVariationalSolver objects. The solver objects can be reused, which saves on recomputing things like a symbolic matrix factorization. This is a substantial performance optimization -- it's essentially the same issue as raised in #31.
The code to solve the Gauss-Newton operator equation for that inverse solver has been factored out into a separate object called `GaussNewtonCG`. This object implements a state machine to apply the preconditioned conjugate gradient method. That should make it easier to inspect how well the solve for the search direction is working.
> use linear problem + solver objects in inverse module

- icepack/models/hybrid.py
- icepack/models/ice_shelf.py
- icepack/models/ice_stream.py
- icepack/models/shallow_ice.py
- icepack/optimization.py
This patch makes the Newton method, which we use to solve the diagnostic equations for several models, into a state machine object. This should make performance tuning and debugging easier, and it makes some progress towards resolving #31 .
> Refactoring optimization solver

- demo/01-synthetic-ice-shelf.ipynb
- demo/02-larsen-ice-shelf.ipynb
- demo/03-synthetic-ice-stream.ipynb
- demo/04-ice-shelf-inverse.ipynb
- demo/05-hybrid-ice-stream.ipynb
- doc/source/design.rst
- doc/source/engineering.rst
- icepack/inverse.py
- icepack/models/damage_transport.py
- icepack/models/heat_transport.py
- icepack/models/hybrid.py
- icepack/models/ice_shelf.py
- icepack/models/ice_stream.py
- icepack/models/mass_transport.py
- icepack/models/shallow_ice.py
- icepack/optimization.py
- icepack/solvers/__init__.py
- icepack/solvers/damage_solver.py
- icepack/solvers/flow_solver.py
- icepack/solvers/heat_transport.py
- icepack/solvers/utilities.py
- test/heat_transport_test.py
- test/hybrid_test.py
- test/ice_shelf_test.py
- test/ice_stream_test.py
- test/inverse_test.py
- test/mass_transport_test.py
- test/shallow_ice_test.py
Resolves #31 by introducing a new class called `FlowSolver`, which is now responsible for actually solving the physics equations. The model objects now only provide a description of what to solve and not how. This is a substantial and breaking change to the API, but I think it's necessary to achieve good performance.
This is a bit of a work in progress; any feedback would be great! Still to do:
> add FlowSolver object

- demo/02-larsen-ice-shelf.ipynb
- demo/04-ice-shelf-inverse.ipynb
- icepack/interpolate.py
- test/grid_data_test.py
Resolves #35 . The results of the demos that use real data are slightly different but the effect is small.
> linear interpolation from gridded data

- icepack/inverse.py
These were uncovered by testing on harder cases than what's in either the test suite or the demos. We should find a way to automate testing on real data.
> bug fixes in Gauss-Newton solver

- doc/source/contributing.rst
- doc/source/style.rst
- icepack/__init__.py
- icepack/interpolate.py
- icepack/inverse.py
- icepack/meshing.py
- icepack/models/__init__.py
- icepack/models/damage_transport.py
- icepack/models/friction.py
- icepack/models/heat_transport.py
- icepack/models/hybrid.py
- icepack/models/ice_shelf.py
- icepack/models/ice_stream.py
- icepack/models/mass_transport.py
- icepack/models/shallow_ice.py
- icepack/models/viscosity.py
- icepack/norms.py
- icepack/optimization.py
- icepack/plot.py
- icepack/solvers/__init__.py
- icepack/solvers/damage_solver.py
- icepack/solvers/flow_solver.py
- icepack/solvers/heat_transport.py
This patch:
* makes a boatload of fixes that I found by running pylint and flake8
* adds a description of how to use these tools to the documentation
> formatting + linter fixes

- icepack/solvers/__init__.py
- icepack/solvers/flow_solver.py
- test/mass_transport_test.py
The switch to the new flow solver interface removed the Lax-Wendroff timestepping scheme. This patch adds it as an option again and makes it the default.
> Lax-Wendroff

- demo/05-ice-shelf-inverse.ipynb
Use the error estimates, rather than the standard deviations, to weight the model-data misfit. This is much more stringent and as a consequence we can't match them to what statistical estimation theory would predict, but I outline the reasons for that at the end. The demo also takes longer to run. But the results are much more interesting -- you can pick out marine ice formation and many more rifts than just the big one near the Gipps Ice Rise.
> Make Larsen inverse more interesting

- .circleci/config.yml
- icepack/datasets.py
This patch changes the testing environment to one that contains real data and executes the tutorial notebook on Larsen C as part of the test suite. In the future I'd like to make it run the inverse problems notebook as well since this is one of the more finicky parts of the code.
> Test with real data

- .circleci/config.yml
Should get rid of a bunch of warnings from PETSc, loopy, and Firedrake.
> New testing environment version

- icepack/statistics.py
- test/statistics_test.py
> Conditionally import ROL & skip stats test if not installed

- .circleci/config.yml
- icepack/constants.py
- icepack/models/hybrid.py
- icepack/models/ice_shelf.py
- icepack/models/ice_stream.py
- icepack/models/shallow_ice.py
- icepack/models/viscosity.py
- icepack/norms.py
- icepack/plot.py
- icepack/utilities.py
- test/depth_average_test.py
- test/heat_transport_test.py
- test/hybrid_test.py
- test/ice_shelf_test.py
- test/ice_stream_test.py
- test/inverse_test.py
- test/mass_transport_test.py
- test/meshing_test.py
- test/norm_test.py
- test/plot_test.py
- test/shallow_ice_test.py
- test/statistics_test.py
This changes the formatting of exponentials `a**b`.
> Switch autoformatter black to version >= 22.0

- notebooks/tutorials/07-rgi-meshing.ipynb
- pyproject.toml
- src/icepack/datasets.py
- src/icepack/meshing.py
- src/icepack/registry-nsidc.txt
- test/meshing_test.py
* Add the Alaska region of the Randolph Glacier Inventory to the fetchable data sets
* Make the outline normalization routines work on polygons in addition to multi-line strings
* Add a test and demo showing how to mesh an outline from RGI
> meshing improvements

- notebooks/tutorials/06-hybrid-ice-stream-xyz.ipynb
These now need an explicit call to the depth average function first
> Fix plotting functions in hybrid model demo

- src/icepack/models/hybrid.py
- src/icepack/models/shallow_ice.py
- test/hybrid_test.py
Resolves #116. Add a test that the hybrid model reproduces SIA when the friction coefficient is very large and corrects a missing factor of 2 in the definition of the effective strain rate.
> Hybrid fix

- src/icepack/optimization.py
- test/statistics_test.py
Add annotation of the icepack `NewtonSolver` using pyadjoint. Reuses the Firedrake `NonlinearVariationalSolve` block. Also add a basic Taylor verification test to `test_ice_shelf_inverse`.
> pyadjoint `NewtonSolver.solve` annotation

- src/icepack/statistics.py
- test/statistics_test.py
Per #129 there's a bug in the MaximumProbabilityEstimator class that's triggered only for problems with more than one controls. Adds a test and fixes this bug.
> Fix stats module for multiple controls

- src/icepack/models/hybrid.py
- src/icepack/models/shallow_ice.py
- src/icepack/models/viscosity.py
Allow the user to specify the flow exponent in Glen's flow law.
> n=? option

- src/icepack/solvers/flow_solver.py
> Make using objective for PETSc line searches optional
